# OPENHAB
OPENHAB_USER: openhab
OPENHAB_USERGROUP: "smarthome"
OPENHAB_HOME: /opt/openhab

OPENHAB_VERSION: 2.4.0
OPENHAB_ARCH: amd64-debian

# ASTERISK
ASTERISK_USER: asterisk
ASTERISK_USERGROUP: "{{OPENHAB_USERGROUP}}"
ASTERISK_CONF_DIR: /opt/asterisk

ASTERISK_SIP_USER: openHAB2
ASTERISK_SIP_PASS: ""
ASTERISK_SIP_HOST: fritz.box
ASTERISK_SIP_EXTENSION: 620

ASTERISK_AMI_USER: openHAB2
ASTERISK_AMI_PASS: ""

# PIHOLE
PIHOLE_USER: pihole
PIHOLE_USERGROUP: "{{OPENHAB_USERGROUP}}"
PIHOLE_CONF_DIR: /opt/pihole
